server:
  port: 8080
  mode: "debug" #debug | release

database:
  host: localhost
  port: 5432
  username: postgres
  password: password
  name: crawliq
  sslmode: disable
  max_conns: 10
  min_conns: 1
  max_conn_lifetime: 30m

crawler:
  worker_count: 50
  request_timeout: "10s"
  max_redirects: 5
  user_agent: "crawliq-bot/1.0 (+https://github.com/yugjain1212/crawliq)"
  per_domain_delay: "0s"
  respect_robots_txt: true
  max_pages_per_crawl: 5000

log:
  level: "info" # debug | info | warn | error
  pretty: true # human readable console output , false = JSON
  
